//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLFindResident.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLFindResident.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\persons.json.
        /// </summary>
        internal static string persons_json {
            get {
                return ResourceManager.GetString("persons.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\receivers.json.
        /// </summary>
        internal static string receivers_json {
            get {
                return ResourceManager.GetString("receivers.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan1.txt.
        /// </summary>
        internal static string scan1 {
            get {
                return ResourceManager.GetString("scan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan10.txt.
        /// </summary>
        internal static string scan10 {
            get {
                return ResourceManager.GetString("scan10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan11.txt.
        /// </summary>
        internal static string scan11 {
            get {
                return ResourceManager.GetString("scan11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan2.txt.
        /// </summary>
        internal static string scan2 {
            get {
                return ResourceManager.GetString("scan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan3.txt.
        /// </summary>
        internal static string scan3 {
            get {
                return ResourceManager.GetString("scan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan4.txt.
        /// </summary>
        internal static string scan4 {
            get {
                return ResourceManager.GetString("scan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan5.txt.
        /// </summary>
        internal static string scan5 {
            get {
                return ResourceManager.GetString("scan5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan6.txt.
        /// </summary>
        internal static string scan6 {
            get {
                return ResourceManager.GetString("scan6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan7.txt.
        /// </summary>
        internal static string scan7 {
            get {
                return ResourceManager.GetString("scan7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan8.txt.
        /// </summary>
        internal static string scan8 {
            get {
                return ResourceManager.GetString("scan8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ED777\source\repos\MLFindResident\MLFindResident\Resources\Data\test ocr\scan9.txt.
        /// </summary>
        internal static string scan9 {
            get {
                return ResourceManager.GetString("scan9", resourceCulture);
            }
        }
    }
}
